services:
  spycat:
    env_file:
      - .env
    build: .
    container_name: spycat
    restart: unless-stopped
    ports:
      - ${PORT}
    networks:
      - postgres-net
      - localnet
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13
    container_name: spycatdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-net

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge
    name: postgres-net

  localnet:
    external: false
    name: localnet

volumes:
  uploads:
  postgres_data: